### ISSUE TITLE
[PE-D][Tester E] Invalid phone number allowed - "add", "edit"

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T12-1/tp#142]
![image.png](https://raw.githubusercontent.com/tayziyi/ped/main/files/88aa7021-c1d8-40a3-a857-87df461b884c.png)

As seen from the screenshot, for "add" and "edit" commands allow phone numbers to be of greater than length 15.
Phone numbers in Singapore context should only allow phone number to be 8 digits long and start with number 8 or 9.
Phone numbers in international context should be of maximum 15 digits.
The team needs to be clear in their user guide which group of target group they are targeting.
In addition, there needs to be a restriction to prevent phone numbers of invalid length from being entered based on their target group.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: tayziyi/ped#7

**Comment by yuechen2001** [comment]
After further research, we realised that the maximum number of digits in any country thus far is 15. 

![image](https://github.com/AY2324S2-CS2103T-T12-1/tp/assets/64315146/00c5d339-9a43-436e-8cf9-080c074cde88)

As seen from this screenshot, the contact card can display way more than 15 digits even in the minimum window size. No important details of a valid phone number are being obscured. Hence, capping the maximum length of a phone number is considered to be a feature enhancement and will not be fixed in this iteration.

Furthermore, we deliberately gave the users free reign over the starting digits of phone numbers, as student developers can be from anywhere in the world and it does not make sense to only restrict savable contacts to those that reside in Singapore. Maybe in future iterations, we can consider adding restrictions based on the user's geographical location
